trigger: none

name: $(Build.SourceBranchName)-$(Date:ddMMyy)-$(Rev:rr)

pool:
 vmImage: windows-latest

parameters:
 - name: configuration
   displayName: "Configuration ex CONFIGURATION_1 "
   type: string
   default: "CONFIGURATION_1"
   values:
    - "__CONFIGURATION_1__"
    - "__CONFIGURATION_2__"
    - "__CONFIGURATION_3__"

 - name: environment
   displayName: "Select Environment "
   type: string
   default: "Stage"
   values:
    - "Stage"
    - "Production"

variables:
 - group : "${{ parameters.environment }}${{ parameters.configuration }}VARIABLES"

stages:
- stage: Building
  displayName: Build
  jobs:
  - job: JobA
    steps:
    - pwsh: |
        $json="{'job1': {'Work': 'work1'}, 'job2': {'Work': 'work2'}}"
        Write-Host "##vso[task.setvariable variable=targets;isOutput=true]$json"
      name: setTargets
    - script: echo $(setTargets.targets)
      name: echovar

  - job: buildSrc
    dependsOn: JobA
    displayName: Build source
    strategy:
      matrix: $[ dependencies.JobA.outputs['setTargets.targets'] ]
    variables:
      targets: $[ dependencies.JobA.outputs['setTargets.targets'] ]
    steps:
    - pwsh: Write-Host "$(targets)"
      displayName: 'Print all variables via expression'