trigger: none

name: $(Build.SourceBranchName)-$(Date:ddMMyy)-$(Rev:rr)

pool:
 vmImage: windows-latest

parameters:
 - name: configuration
   displayName: "Configuration ex CONFIGURATION_1 "
   type: string
   default: "CONFIGURATION_1"
   values:
    - "CONFIGURATION_1"
    - "CONFIGURATION_2"
    - "CONFIGURATION_3"

 - name: environment
   displayName: "Select Environment "
   type: string
   default: "Stage"
   values:
    - "Stage"
    - "Production"

variables:
 - group : "${{ parameters.environment }}${{ parameters.configuration }}VARIABLES"

stages:
- stage: Building
  displayName: Build
  jobs:
  - job: CompilingCode
    workspace:
      clean: all
    timeoutInMinutes: 360
    displayName: Building
    steps:
    - task: PowerShell@2
      inputs:
        arguments: '-firstname $(Key1)'